### PR TITLE
do not run verify when there are compilation errors or warnings

### LINKED ISSUE #6: Build errors being swallowed by verify
The verify build plugin is swallowing any build errors. Before verifying it should check to see if there were any problems (`stats.compilation.warnings`)

https://github.com/Financial-Times/n-webpack/blob/master/lib/addons/verify-build.js#L30

### PR DESCRIPTION
**Pull request by i-like-robots**
fixes #6 

screen shot 2016-06-23 at 13 40 30

### CODE REVIEW

**Comment by i-like-robots** [comment]
CC @aintgoin2goa

**Comment by ironsidevsquincy** [comment]
Cool. And that will output the actual error?

**Comment by bjfletcher** [comment]
image

**Comment by bjfletcher** [comment]
PS I'm not a cat person, but I have reason to believe that @i-like-robots is ;)

**Comment by i-like-robots** [comment]
Yes, the standard webpack output will be displayed.

Another solution may be to append an error to the compilation instead of throwing an error - with Webpack set to `--bail` (which it is when running `build-production`) this should still kill a build.

**Comment by i-like-robots** [comment]
And, @bjfletcher I'm actually quite allergic to cats =[

**Pull request merged**
